# Generated by Django 4.0.1 on 2022-01-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=100)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentcontact', models.CharField(max_length=15)),
            ],
        ),
    ]
