# Generated by Django 4.0.1 on 2022-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0003_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='StudentsInformation',
        ),
        migrations.AlterField(
            model_name='registration',
            name='lname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='minitial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
