# Generated by Django 4.0.1 on 2022-01-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('idnum', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('minitial', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('cpnumber', models.DecimalField(decimal_places=0, max_digits=11)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('bdate', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
