# Generated by Django 4.0.1 on 2022-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='section',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='bdate',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cpnumber',
            field=models.DecimalField(decimal_places=0, default='', max_digits=11),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='minitial',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
