# Generated by Django 4.0.1 on 2022-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0002_registration_section_alter_registration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=20)),
                ('datereq', models.CharField(default='', max_length=20)),
                ('document', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
