# Generated by Django 4.0.1 on 2022-02-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0002_yves_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yves',
        ),
    ]
