# Generated by Django 4.0.1 on 2022-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0003_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
