# Generated by Django 4.0.1 on 2022-01-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0004_alter_certification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='course',
            new_name='cert_course',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='datereq',
            new_name='cert_datereq',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='document',
            new_name='cert_document',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='email',
            new_name='cert_email',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='fullname',
            new_name='cert_fullname',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='status',
            new_name='cert_status',
        ),
    ]
