# Generated by Django 4.0.1 on 2022-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0005_rename_course_certification_cert_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='cert_course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_datereq',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_document',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_status',
            field=models.CharField(max_length=20),
        ),
    ]
