# Generated by Django 4.0.1 on 2022-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0007_rename_certification_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='field',
            field=models.CharField(default='', max_length=20),
        ),
    ]
