# Generated by Django 4.0.1 on 2022-01-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0009_alter_certifications_cert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nstpApp.registration'),
        ),
    ]
