# Generated by Django 4.0.1 on 2022-01-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0010_certifications_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='cert_status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED')], default='Pending', max_length=20),
        ),
    ]
