# Generated by Django 4.0.1 on 2022-01-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0012_rename_cert_email_certifications_idnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.EmailField(max_length=254, null=True)),
                ('cert_fullname', models.CharField(max_length=100)),
                ('cert_course', models.CharField(max_length=20)),
                ('cert_datereq', models.CharField(max_length=20)),
                ('cert_document', models.CharField(max_length=20)),
                ('cert_status', models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED')], default='Pending', max_length=20)),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nstpApp.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='certifications',
        ),
    ]
