# Generated by Django 4.0.1 on 2022-01-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0013_certification_delete_certifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certification',
            new_name='certifications',
        ),
    ]
