# Generated by Django 4.0.1 on 2022-01-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0014_rename_certification_certifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifications',
            old_name='idnumber',
            new_name='cert_email',
        ),
    ]
