# Generated by Django 4.0.1 on 2022-01-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0015_rename_idnumber_certifications_cert_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='registration',
        ),
    ]
