# Generated by Django 4.0.1 on 2022-02-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0017_alter_certifications_cert_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='platoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.CharField(max_length=20)),
                ('bravo', models.CharField(max_length=20)),
                ('charlie', models.CharField(max_length=20)),
                ('delta', models.CharField(max_length=20)),
                ('echo', models.CharField(max_length=20)),
                ('foxtrot', models.CharField(max_length=20)),
                ('golf', models.CharField(max_length=20)),
                ('hotel', models.CharField(max_length=20)),
                ('india', models.CharField(max_length=20)),
                ('juliet', models.CharField(max_length=20)),
                ('kilo', models.CharField(max_length=20)),
                ('lima', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='certifications',
            name='cert_status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED')], default='Pending', max_length=20),
        ),
    ]
