# Generated by Django 3.0.14 on 2022-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0017_alter_certifications_cert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='cert_status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
