# Generated by Django 4.0.1 on 2022-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0018_platoons_alter_certifications_cert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platoons',
            name='alpha',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='platoons',
            name='bravo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='platoons',
            name='charlie',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='platoons',
            name='delta',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='platoons',
            name='echo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='platoons',
            name='foxtrot',
            field=models.CharField(max_length=200),
        ),
    ]
