# Generated by Django 4.0.1 on 2022-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0019_alter_platoons_alpha_alter_platoons_bravo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platoons',
            name='bravo',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='charlie',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='echo',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='foxtrot',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='golf',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='india',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='juliet',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='kilo',
        ),
        migrations.RemoveField(
            model_name='platoons',
            name='lima',
        ),
        migrations.AlterField(
            model_name='certifications',
            name='cert_status',
            field=models.CharField(max_length=20),
        ),
    ]
