# Generated by Django 4.0.1 on 2022-02-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0022_alter_certifications_cert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='cert_status',
            field=models.CharField(choices=[('PENDING', 'PENDING '), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20),
        ),
    ]
