# Generated by Django 4.0.1 on 2022-02-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0025_bravo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bravo',
            new_name='alphamodel',
        ),
        migrations.RenameModel(
            old_name='alpha',
            new_name='baravomodel',
        ),
    ]
