# Generated by Django 4.0.1 on 2022-02-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0026_rename_bravo_alphamodel_rename_alpha_baravomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='baravomodel',
            new_name='bravomodel',
        ),
    ]
