# Generated by Django 4.0.1 on 2022-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0027_rename_baravomodel_bravomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='charliemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='deltamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='echomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='foxtrotmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='golfmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='hotelmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='indiamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='julietmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='kilomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='limaomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
