# Generated by Django 4.0.1 on 2022-02-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0028_charliemodel_deltamodel_echomodel_foxtrotmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='limaomodel',
            new_name='limamodel',
        ),
    ]
