# Generated by Django 3.0.14 on 2022-02-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0029_rename_limaomodel_limamodel'),
        ('nstpApp', '0018_auto_20220204_2321'),
    ]

    operations = [
    ]
