# Generated by Django 4.0.1 on 2022-02-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0018_auto_20220204_2321'),
        ('nstpApp', '0029_rename_limaomodel_limamodel'),
    ]

    operations = [
    ]
