# Generated by Django 4.0.1 on 2022-02-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0030_merge_20220206_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='certifications',
            name='cert_status',
            field=models.CharField(choices=[('PENDING', 'PENDING '), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
