# Generated by Django 4.0.1 on 2022-02-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0031_sample_alter_certifications_cert_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample',
            new_name='sample1',
        ),
    ]
