# Generated by Django 4.0.1 on 2022-02-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0032_rename_sample_sample1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample1',
        ),
    ]
